services:
  web:
    build: .
    environment:
      - HOST=odoo-community-hub-ufd0dz
      - USER=odoo
      - PASSWORD=5edw5jsxgauc0ito
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    # ¡QUITAMOS EL ARRASTRE DEL COMMAND DE AQUÍat!
    # El ENTRYPOINT del Dockerfile se encargará de ejecutar /startup.sh

volumes:
  odoo-web-data: