services:
  web:
    build: .
    environment:
      - HOST=odoo-community-hub-ufd0dz
      - USER=odoo
      - PASSWORD=5edw5jsxgauc0ito
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    command:
      - odoo
      - -c
      - /etc/odoo/odoo.conf
      - --db_host=odoo-community-hub-ufd0dz
      - --db_user=odoo
      - --db_password=5edw5jsxgauc0ito
      - --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/server-tools,/mnt/extra-addons/web-18.0,/mnt/extra-addons/dms,/mnt/extra-addons/custom
      - --init=base

volumes:
  odoo-web-data:
