[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/server-tools,/mnt/extra-addons/web-18.0,/mnt/extra-addons/dms,/mnt/extra-addons/custom
db_host = odoo-community-hub-ufd0dz
db_user = odoo
db_password = 5edw5jsxgauc0ito
db_port = 5432
data_dir = /var/lib/odoo
proxy_mode = True