[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/server-tools,/mnt/extra-addons/web-18.0,/mnt/extra-addons/dms,/mnt/extra-addons/custom
db_host = odoo-community-hub-ufd0dz
db_port = 5432
db_user = odoo
db_password = 5edw5jsxgauc0lto
data_dir = /var/lib/odoo
limit_time_cpu = 600
limit_time_real = 1200
# workers = 2
# max_cron_workers = 1
proxy_mode = True
