[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/opt/odoo/workspace/extra-addons/server-tools,/opt/odoo/workspace/extra-addons/web-18.0
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
